### ISSUE TITLE
Implement formatting traits

### ISSUE THREAD

**Issue by danlehmann** [danlehmann/arbitrary-int#21]
It is not currently possible to easily print arbitrary-ints through for example `{:x}`.

Ensure that all typical formatting operations are available

**Comment by hecatia-elegua** [comment]
https://github.com/rust-ux/uX/blob/31b5d11b884a77f4ed78db7a298526eca0fc80a4/src/lib.rs#L211

**Comment by danlehmann** [comment]
Ord, PartialOrd, Eq, PartialEq are already done.

Need Octal, Binary, Hash
