### ISSUE TITLE
Rename "nightly" feature

### ISSUE THREAD

**Issue by danlehmann** [danlehmann/arbitrary-int#22]
const_trait has been removed from upstream Rust, so on a new compiler nightly no longer builds (for example, `From<>` is no longer const). There is currently no alternative, so we just probably just remove this optional feature

**Comment by danlehmann** [comment]
Just to clarify why this is a problem: When using a current nightly compiler (I am testing nightly-2023-04-20), arbitrary-int using the "nightly" feature fails to build as it relies on:

```
error[E0635]: unknown feature `const_convert`
 --> /Users/daniel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arbitrary-int-1.2.5/src/lib.rs:2:42
  |
2 | #![cfg_attr(feature = "nightly", feature(const_convert, const_trait_impl))]
  |                                          ^^^^^^^^^^^^^

error: const `impl` for trait `From` which is not marked with `#[const_trait]`
   --> /Users/daniel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/arbitrary-int-1.2.5/src/lib.rs:789:67
    |
789 |             impl<const BITS: usize, const BITS_FROM: usize> const From<UInt<$from, BITS_FROM>>
    |                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
865 | from_arbitrary_int_impl!(u8, [u16, u32, u64, u128]);
    | --------------------------------------------------- in this macro invocation
    |
    = note: marking a trait with `#[const_trait]` ensures all default method bodies are `const`
    = note: adding a non-const method body in the future would be a breaking change
    = note: this error originates in the macro `from_arbitrary_int_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by danlehmann** [comment]
Thanks! Let's rename the feature then? We can add a comment saying that this is requires an old compiler

**Comment by danlehmann** [comment]
Out of curiosity, which part of your code relies on this? In bitbybit, I completely side-stepped Number by entirely relying on `.value()` and the knowledge of how many bits e.g. a u5 is (by looking at the name). I assume in your case that wouldn't work bitenums?

**Comment by hecatia-elegua** [comment]
One example is `<Self as arbitrary_int::Number>::MAX.value()`. I also use `new` in const context, not sure where rn and I need some sleep

**Comment by danlehmann** [comment]
@hecatia-elegua please see https://github.com/danlehmann/arbitrary-int/pull/27. Does this work for you?
