### ISSUE TITLE
possible typo in `CompileTimeAssert::SMALLER_THAN`

### ISSUE THREAD

**Issue by pickx** [danlehmann/arbitrary-int#24]
both `CompileTimeAssert::SMALLER_THAN_EQUAL` and `CompileTimeAssert::SMALLER_THAN` assert that `A <= B`.

hopefully I didn't miss something obvious, but I'd expect `SMALLER_THAN` to assert that `A < B`.

**Comment by danlehmann** [comment]
Hey, nice find! Luckily, not much is broken in practice. The only result is that the following call is possible:

`let a: u7 = u7::new(1).widen()`

Which is - while pointless - also fine.

I'll upload a patch to make widen officially support equal bitlengths and remove the SMALLER_THAN check. This way if anyone's using the current behavior (e.g. in autogenerated code) things will work as before.
