### ISSUE TITLE
Range iterators?

### ISSUE THREAD

**Issue by pickx** [danlehmann/arbitrary-int#29]
Currently it is not possible to do something like
```rust
for n in u5::MIN..u5::MAX {
    //...
}
```

Implementing this would be possible if/when [`step_trait`](https://github.com/rust-lang/rust/issues/42168) is stable.

Alternatively it is possible to create a new range-like type which implements `IntoIterator`, produced by something like `u5::range(u5::MIN, u5::MAX)`. The downside of course is that this function would become unnecessary if `step_trait` is stabilized.

**Comment by danlehmann** [comment]
Hey, thanks for filing the feature request. I am happy to add an optional feature to support step_trait. I actually have that need from time to time as well.

I'm planning to get this in within a few days.

**Comment by pickx** [comment]
> Hey, thanks for filing the feature request. I am happy to add an optional feature to support step_trait. I actually have that need from time to time as well.
> 
> I'm planning to get this in within a few days.

if that is okay with you - I have implemented this already, so perhaps I can open a PR and see whatever additional changes it require.

**Comment by danlehmann** [comment]
Oh awesome! Sure, please send over a PR

**Comment by danlehmann** [comment]
Merged it. Do you want this published on crates.io right away or is it enough to roll this into whatever is the next version?

**Comment by pickx** [comment]
thanks for merging. I don't need this right now, so feel free to push this whenever you want.

**Comment by danlehmann** [comment]
Sounds good. Thanks again for your contribution!
