### ISSUE TITLE
provide const_trait_impls behind a gate

### ISSUE THREAD

**Issue by hecatia-elegua** [danlehmann/arbitrary-int#8]
It would be nice of you if you could provide all the trait impls as const.
Currently afaik all the bitops, maybe from impls and the Number trait would be useful as const.
Not entirely sure how easy it is to put this behind a feature gate or something like that.
Otherwise I have to vendor somehow or just work without const for a while.
Thank you for your time.

**Comment by danlehmann** [comment]
Hey and sorry for the late response. Some things came up in my life which will prevent me from working on this for a while.

If you'd like to submit a patch, I'd be happy to review it though.

**Comment by hecatia-elegua** [comment]
It's all good bro, your life is more important.
I'll see about the patch, not sure if it's possible to feature gate based on stable/nightly though.
